version: "3"
services:

  pg:
    image: postgres:latest
    container_name: pg
    ports:
      - "6500:5432"
    env_file:
      - ./.env
    volumes:
      - ./volumes/pg:/var/lib/postgresql/data:rw

  pg-admin:
    image: dpage/pgadmin4
    container_name: pg-admin
    env_file:
      - ./.env
    ports:
      - "5050:80"
    user: '$UID:$GID'
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin:rw