version: "3"
services:
  pg:
    image: postgres:latest
    restart: always
    container_name: pg
    ports:
      - "6500:5432"
    env_file:
      - ./.env
    volumes:
      - type: volume
        source: data-volume
        target: /var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 6501:8080

volumes:
 data-volume: